### ISSUE TITLE
Error with Pioneer 3 AT and Tiago Sims: Could not find parameter robot_description

### ISSUE THREAD

**Issue by G-Conard** [cyberbotics/webots_ros#128]
First off, this is great stuff here! I'm excited to continue digging into this and using it for my own projects.

However, I ran into a problem running the Pioneer 3 AT simulation as shown in the sample tutorials (http://wiki.ros.org/webots_ros/Tutorials/Sample%20Simulations).  When I run it, the Webots application opens and displays the robot, but I am unable to get it to respond to the `gmapping` or `teleop_twist_keyboard` commands.  I get this output in the Ubuntu terminal:

```
... logging to /home/conardg/.ros/log/345969f2-264c-11ed-a8f1-6da61b464bff/roslaunch-conardg-ThinkBook-Ubuntu-14947.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://conardg-ThinkBook-Ubuntu:42023/

SUMMARY
========

PARAMETERS
 * /pioneer_diff_drive_controller/left_wheel: ['front left whee...
 * /pioneer_diff_drive_controller/pose_covariance_diagonal: [0.001, 0.001, 10...
 * /pioneer_diff_drive_controller/right_wheel: ['front right whe...
 * /pioneer_diff_drive_controller/twist_covariance_diagonal: [0.001, 0.001, 10...
 * /pioneer_diff_drive_controller/type: diff_drive_contro...
 * /rosdistro: noetic
 * /rosversion: 1.15.14

NODES
  /
    controller_spawner (controller_manager/spawner)
    example_state_publisher (robot_state_publisher/robot_state_publisher)
    pioneer_lidar_tf (tf/static_transform_publisher)
    webots (webots_ros/webots_launcher.py)

auto-starting new master
process[master]: started with pid [14962]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 345969f2-264c-11ed-a8f1-6da61b464bff
process[rosout-1]: started with pid [14979]
started core service [/rosout]
process[controller_spawner-2]: started with pid [14986]
process[webots-3]: started with pid [14987]
process[example_state_publisher-4]: started with pid [14988]
process[pioneer_lidar_tf-5]: started with pid [14989]
[ERROR] [1661634426.048904973]: Could not find parameter robot_description on parameter server
[INFO] [1661634426.297805]: Controller Spawner: Waiting for service controller_manager/load_controller
[example_state_publisher-4] process has died [pid 14988, exit code 1, cmd /opt/ros/noetic/lib/robot_state_publisher/robot_state_publisher __name:=example_state_publisher __log:=/home/conardg/.ros/log/345969f2-264c-11ed-a8f1-6da61b464bff/example_state_publisher-4.log].
log file: /home/conardg/.ros/log/345969f2-264c-11ed-a8f1-6da61b464bff/example_state_publisher-4*.log
[example_state_publisher-4] restarting process
process[example_state_publisher-4]: started with pid [15050]
[ERROR] [1661634431.383425751]: Could not find parameter robot_description on parameter server
[example_state_publisher-4] process has died [pid 15050, exit code 1, cmd /opt/ros/noetic/lib/robot_state_publisher/robot_state_publisher __name:=example_state_publisher __log:=/home/conardg/.ros/log/345969f2-264c-11ed-a8f1-6da61b464bff/example_state_publisher-4.log].
log file: /home/conardg/.ros/log/345969f2-264c-11ed-a8f1-6da61b464bff/example_state_publisher-4*.log
[INFO] [1661634431.724358]: Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [1661634431.726992]: Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [1661634431.728499]: Loading controller: pioneer_diff_drive_controller
[INFO] [1661634431.752464]: Controller Spawner: Loaded controllers: pioneer_diff_drive_controller
[INFO] [1661634431.784391]: Started controllers: pioneer_diff_drive_controller
[example_state_publisher-4] restarting process
process[example_state_publisher-4]: started with pid [15103]
^C[example_state_publisher-4] killing on exit
[pioneer_lidar_tf-5] killing on exit
[controller_spawner-2] killing on exit
[webots-3] killing on exit
[INFO] [1661634636.332665]: Shutting down spawner. Stopping and unloading controllers...
[INFO] [1661634636.335120]: Stopping all controllers...
[WARN] [1661634636.496830]: Controller Spawner error while taking down controllers: unable to connect to service: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/webots_ros/webots_launcher.py", line 49, in <module>
    subprocess.call(command)
  File "/usr/lib/python3.8/subprocess.py", line 342, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1806, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.8/subprocess.py", line 1764, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

I think the primary issue is `[ERROR] [1661634426.048904973]: Could not find parameter robot_description on parameter server`.  I do not know if I set something up wrong or if something is missing in the launch file.  I ran into similar errors with the Tiago simulation.  The other sample simulations worked fine.

**Comment by eslamsherif5** [comment]
Have you found a solution for this problem? @G-Conard

**Comment by eslamsherif5** [comment]
I solved it by exporting `WEBOTS_HOME` using `export WEBOTS_HOME=/usr/local/webots`

**Comment by warmsh** [comment]
> 我通过使用导出来解决它`WEBOTS_HOME``export WEBOTS_HOME=/usr/local/webots`

Have you completely solved the problem? I set up WEBOTS_HOME but still have the above problem, do you know the reason?

**Comment by tl123987** [comment]
> > 我通过使用导出来解决它`` WEBOTS_HOME``export WEBOTS_HOME=/usr/local/webots ``
> 
> Have you completely solved the problem? I set up WEBOTS_HOME but still have the above problem, do you know the reason?

hello,Have you completely solved the problem?
